name: release-from-pom

on:
  push:
    branches: [ "main", "master" ]   # ajuste se seu branch principal é outro
  workflow_dispatch:

permissions:
  contents: write   # necessário para criar tag e release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # precisamos de tags

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Read version from pom.xml
        id: ver
        run: |
          VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          CLEAN_VERSION="${VERSION/-SNAPSHOT/}"
          TAG="v${CLEAN_VERSION}"

          echo "VERSION=${VERSION}"           >> $GITHUB_ENV
          echo "CLEAN_VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV
          echo "TAG=${TAG}"                   >> $GITHUB_ENV

          echo "version=${VERSION}"           >> $GITHUB_OUTPUT
          echo "clean=${CLEAN_VERSION}"       >> $GITHUB_OUTPUT
          echo "tag=${TAG}"                   >> $GITHUB_OUTPUT

      - name: Decide final tag (avoid collision)
        id: decide
        run: |
          git fetch --tags --force
          FINAL_TAG="${TAG}"
          if git rev-parse "${FINAL_TAG}" >/dev/null 2>&1; then
            FINAL_TAG="${TAG}-build.${GITHUB_RUN_NUMBER}"
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "Tag ${TAG} existe; usando ${FINAL_TAG}"
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
            echo "Usando tag ${FINAL_TAG}"
          fi
          echo "FINAL_TAG=${FINAL_TAG}" >> $GITHUB_ENV
          echo "final_tag=${FINAL_TAG}" >> $GITHUB_OUTPUT

      - name: Build with Maven (Java 8)
        run: mvn -B -DskipTests package

      - name: Create Git tag
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "${FINAL_TAG}" -m "Release ${FINAL_TAG} (from pom ${VERSION})"
          git push origin "${FINAL_TAG}"

      - name: Upload artifacts (job history)
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            target/*-shaded.jar
            target/*.jar
          if-no-files-found: warn

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FINAL_TAG }}
          name: ${{ env.FINAL_TAG }}
          files: |
            target/*-shaded.jar
            target/*.jar
          generate_release_notes: true
          prerelease: ${{ env.PRERELEASE == 'true' }}
